{% set name = "floatcsep" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/floatcsep-{{ version }}.tar.gz
  sha256: 182584aa45e696238e8489fce5dd6c148c61d3e5e04c836ae88ea034d05b51ce

build:
  entry_points:
    - floatcsep = floatcsep.commands.main:floatcsep
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=52.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<=3.12
    - numpy
    - pycsep
    - dateparser
    - docker-py
    - git
    - gitpython
    - h5py
    - matplotlib-base
    - panel
    - pip
    - pyshp
    - pyyaml
    - requests
    - scipy
    - seaborn
    - pytables
    - xmltodict
    - weasyprint
    - markdown-it-py

test:
  imports:
    - floatcsep
  commands:
    - pip check
    - floatcsep --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cseptesting/floatcsep.git
  summary: CSEP Floating Experiment application
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pabloitu
    - pciturri
